### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by mmcghee18** [greydanus/scribe#8]
Hi! 👋 

How long does training the model typically take (following the instructions in the README.md) on a GPU device (I'm using Microsoft Azure)? What is the expected output, and how would one use that output to then generate handwriting sequences? Just trying to get a sense of whether I'm doing this correctly.

Thanks!

**Comment by greydanus** [comment]
Hi Michelle, to be honest, this code kind of sucks! I wrote it two years ago when I was still learning TensorFlow. At this point, it's pretty outdated. I'll be releasing a new version soon that I've written entirely in PyTorch. It's far better. In the meantime, I suggest you try writing your own version (hard but worth it) or use someone else's implementation :)
